apiVersion: v1
kind: Service
metadata:
  name: {{ include "switchyard.fullname" . }}
  namespace: {{ include "switchyard.namespace" . }}
  labels:
    {{- include "switchyard.labels" (dict "root" . "component" "server") | nindent 4 }}
spec:
  type: {{ .Values.serviceType }}
  ports:
    - port: {{ .Values.switchyard.port }}
      targetPort: {{ .Values.switchyard.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "switchyard.selectorLabels" (dict "root" . "component" "server") | nindent 4 }}