apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "configurator.fullname" . }}
  namespace: {{ include "switchyard.namespace" . }}
  labels:
    {{- include "switchyard.labels" (dict "root" . "component" "configurator") | nindent 4 }}