apiVersion: v1
kind: Service
metadata:
  name: {{ include "configurator.fullname" . }}
  namespace: {{ include "switchyard.namespace" . }}
  labels:
    {{- include "switchyard.labels" (dict "root" . "component" "configurator") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.configurator.port }}
      targetPort: {{ .Values.configurator.port }}
      protocol: TCP
  selector:
    {{- include "switchyard.selectorLabels" (dict "root" . "component" "configurator") | nindent 4 }}